# ################# #
# Moreblocks Config #
# ################# #
# 'ItemType' - Item to use for viewing blocks in the MoreBlocks menu.
# Instrument types listed by note numbers changing '#NA' to the CustomModelData value to load the block in the MoreBlocks menu.
ItemType: BRICK
HARP:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
BASEDRUM:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
SNARE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
HAT:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
BASS:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
FLUTE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
BELL:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
GUITAR:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
CHIME:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
XYLOPHONE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
IRON_XYLOPHONE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
COW_BELL:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
DIDGERIDOO:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
BIT:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
BANJO:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'
PLING:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
  '13': '#NA'
  '14': '#NA'
  '15': '#NA'
  '16': '#NA'
  '17': '#NA'
  '18': '#NA'
  '19': '#NA'
  '20': '#NA'
  '21': '#NA'
  '22': '#NA'
  '23': '#NA'