# ################# #
# Moreblocks Config #
# ################# #
# 'ItemType' - Item to use for viewing blocks in the MoreBlocks menu.
# Instrument types listed by note numbers changing '#NA' to the CustomModelData value will load the block in the MoreBlocks menu.
ItemType: BRICK
PIANO:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
BASS_DRUM:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
SNARE_DRUM:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
STICKS:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
BASS_GUITAR:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
FLUTE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
BELL:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
GUITAR:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
CHIME:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
XYLOPHONE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
IRON_XYLOPHONE:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
COW_BELL:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
DIDGERIDOO:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
BIT:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
BANJO:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'
PLING:
  '0': '#NA'
  '1': '#NA'
  '2': '#NA'
  '3': '#NA'
  '4': '#NA'
  '5': '#NA'
  '6': '#NA'
  '7': '#NA'
  '8': '#NA'
  '9': '#NA'
  '10': '#NA'
  '11': '#NA'
  '12': '#NA'